passwd=7wyuuofto0ZWEYzeXKdB2+vmOmXwlLOVizxni9LGcxXZnFZ4EqSzOU2Z2SP2q3WtTHu5pRWPzR7RyHTwmZ5oiy3o2udHnmot
key.alias=debug
key.passwd=iLJ7FYeqxv4i1Mun3D3eEOD6sPbQ2NbzEJlHPXE6gHSGvyMqNkF2BcLeeIsz7/6/JxkHrOQRXua6CSkTimBB/DXIUk+HBEU9
